Develop
Pa11ady/java-explore-with-me pull request #2
Opened 2022-10-31 12:38 UTC by Pa11ady

2022-10-31 18:08 UTC, EvgenyKoptubenko commented on README.md
> +
Когда проект настолько велик, то нужна документация как запустить проект из коробки.
Сейчас при локальном запуске падает
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

2022-10-31 19:08 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explorewithme/common/handler/ErrorHandler.java
> +    @ExceptionHandler
Можно перечислять эксепшены через запятую. https://www.baeldung.com/exception-handling-for-rest-with-spring

2022-10-31 19:30 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explorewithme/compilation/CompilationController.java
> +        log.info("{}: {};  получение подборок с {} в количестве {}",
Есть логирование в каждом методе контроллера.
Замечание из разряда "можно лучше" - можно попробовать сделать логирование средством Spring https://www.baeldung.com/spring-http-logging
Тогда настройка логирования будет в одном месте и Spring будет сам логировать, а код будет меньше

2022-10-31 19:44 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explorewithme/event/EventRepository.java
> +    @Query("SELECT e FROM Event AS e " +
старайся не делать переменные в одну букву - плохая привычка. Сейчас, когда селект в три строчки это ничего, но потом, когда будут запросы по две страницы, это может сыграть в минус, т.к. сложно будет найти что это за переменная е и где она объявляется.

2022-10-31 19:45 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explorewithme/event/EventServiceImp.java
> +        rangeStart = (rangeStart != null) ? rangeStart : LocalDateTime.now();
большой кусок кода дублируется

2022-10-31 19:45 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explorewithme/event/EventServiceImp.java
> +        if (updateEventRequest.getAnnotation() != null) {
тут тоже дублирование кода

2022-10-31 19:46 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explorewithme/event/State.java
> +    CANCELED;
тут точка с запятой не нужны

2022-10-31 20:00 UTC, EvgenyKoptubenko commented on docker-compose.yml
> +  stats-service:
При запуске падает

2022-10-31T19:58:17.010821096Z org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided by plugin null

2022-10-31 20:01 UTC, EvgenyKoptubenko requested changes
Падает при запуске через докер

2022-11-01 10:15 UTC, Pa11ady commented on docker-compose.yml
> +  stats-service:
Несколько раз проверял свежий скачанный проект из гита докере работает.
Если бы были бы проблемы с докером, то тесты на гите при создание PR успешно не прошли бы.

2022-11-01 10:17 UTC, Pa11ady commented on README.md
> +
Ок. добавил инструкцию.

2022-11-01 10:52 UTC, Pa11ady commented on main-service/src/main/java/ru/practicum/explorewithme/common/handler/ErrorHandler.java
> +    @ExceptionHandler
ок

2022-11-01 10:54 UTC, Pa11ady commented on main-service/src/main/java/ru/practicum/explorewithme/compilation/CompilationController.java
> +        log.info("{}: {};  получение подборок с {} в количестве {}",
Может быть привычка, когда писал сначала пустые контролеры, чтобы было куда поставить точку останова.

2022-11-01 11:16 UTC, Pa11ady commented on main-service/src/main/java/ru/practicum/explorewithme/event/EventRepository.java
> +    @Query("SELECT e FROM Event AS e " +
поправил

2022-11-01 12:17 UTC, Pa11ady commented on main-service/src/main/java/ru/practicum/explorewithme/request/RequestController.java
> +    @GetMapping("/{userId}/requests")
ок

2022-11-01 12:18 UTC, Pa11ady commented on main-service/src/main/java/ru/practicum/explorewithme/event/State.java
> +    CANCELED;
очепятку не заметил

2022-11-01 14:21 UTC, Pa11ady commented on main-service/src/main/java/ru/practicum/explorewithme/event/EventServiceImp.java
> +        rangeStart = (rangeStart != null) ? rangeStart : LocalDateTime.now();
ок

2022-11-01 15:11 UTC, Pa11ady commented on main-service/src/main/java/ru/practicum/explorewithme/event/EventServiceImp.java
> +        if (updateEventRequest.getAnnotation() != null) {
Если речь про проверку, то она действительно повторяется. Если речь про обновление. то нельзя написать общий код так как AdminUpdateEventRequest UpdateEventRequest разные DTO по условию, хотя часть полей совпадает.

2022-11-01 19:42 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2022-11-02 13:49 UTC, merged